### ISSUE TITLE
docker里面用脚本reqsign_ext.sh生成证书,国密浏览器打开页面失败

### ISSUE THREAD

**Issue by 22826165** [zhaoxiaomeng/Nginx-with-GmSSLv3#1]
nginx error.log如下：
src/http/ngx_http_request.c 221: ngx_http_init_connection
src/http/ngx_http_request.c 221: ngx_http_init_connection
src/http/ngx_http_request.c 660: ngx_http_ssl_handshake
src/event/ngx_event_gmssl.c:479:ngx_ssl_create_connection():
src/event/ngx_event_gmssl.c:518:ngx_ssl_create_connection():
src/event/ngx_event_gmssl.c:568:ngx_ssl_handshake():
last_decrypted_block: B79C912A5A840A0A0A0A0A0A0A0A0A0A
Record
    ContentType: Handshake (22)
    Version: TLCP (1.1)
    Length: 47
    Handshake
        Type: ClientHello (1)
        Length: 43
        ClientHello
            Version: TLCP (1.1)
            Random
                gmt_unix_time : Sat Aug 27 12:12:39 2050
                random: 00337A8E9B06EB9AF1F80D4E24A62214F5C20D02C0074D7F01F8E4BB
            SessionID: (null)
            CipherSuites
                (null) (0x8a8a)
                TLCP_ECC_SM4_CBC_SM3 (0xe013)
            CompressionMethods
                no_compression (0)

/GmSSL-develop/src/tls12.c:697:tls12_accept():
src/event/ngx_event_gmssl.c:598:ngx_ssl_handshake():
src/http/ngx_http_request.c 802: ngx_http_ssl_handshake_handler
src/event/ngx_event_gmssl.c:1402:ngx_ssl_shutdown():
src/http/ngx_http_request.c 660: ngx_http_ssl_handshake
src/event/ngx_event_gmssl.c:479:ngx_ssl_create_connection():
src/event/ngx_event_gmssl.c:518:ngx_ssl_create_connection():
src/event/ngx_event_gmssl.c:568:ngx_ssl_handshake():
last_decrypted_block: B79C912A5A840A0A0A0A0A0A0A0A0A0A
Record
    ContentType: Handshake (22)
    Version: TLCP (1.1)
    Length: 47
    Handshake
        Type: ClientHello (1)
        Length: 43
        ClientHello
            Version: TLCP (1.1)
            Random
                gmt_unix_time : Tue Apr 17 20:10:18 2057
                random: 6BF8416B3F84A7BE6F55D3F304B56E0AE2E544F90338EBD6AB98FC4A
            SessionID: (null)
            CipherSuites
                (null) (0xbaba)
                TLCP_ECC_SM4_CBC_SM3 (0xe013)
            CompressionMethods
                no_compression (0)

/GmSSL-develop/src/tls12.c:697:tls12_accept():
src/event/ngx_event_gmssl.c:598:ngx_ssl_handshake():
src/http/ngx_http_request.c 802: ngx_http_ssl_handshake_handler
src/event/ngx_event_gmssl.c:1402:ngx_ssl_shutdown():
src/http/ngx_http_request.c 221: ngx_http_init_connection
src/http/ngx_http_request.c 660: ngx_http_ssl_handshake
src/event/ngx_event_gmssl.c:479:ngx_ssl_create_connection():
src/event/ngx_event_gmssl.c:518:ngx_ssl_create_connection():
src/event/ngx_event_gmssl.c:568:ngx_ssl_handshake():
last_decrypted_block: B79C912A5A840A0A0A0A0A0A0A0A0A0A
Record
    ContentType: Handshake (22)
    Version: TLCP (1.1)
    Length: 47
    Handshake
        Type: ClientHello (1)
        Length: 43
        ClientHello
            Version: TLCP (1.1)
            Random
                gmt_unix_time : Sun Mar  8 14:29:40 1987
                random: 188B18A5E0F0D5832EF74D7B95D746E735EEE1150D3E7E92705C5D95
            SessionID: (null)
            CipherSuites
                (null) (0x5a5a)
                TLCP_ECC_SM4_CBC_SM3 (0xe013)
            CompressionMethods
                no_compression (0)

/GmSSL-develop/src/tls12.c:697:tls12_accept():
src/event/ngx_event_gmssl.c:598:ngx_ssl_handshake():
src/http/ngx_http_request.c 802: ngx_http_ssl_handshake_handler
src/event/ngx_event_gmssl.c:1402:ngx_ssl_shutdown():
src/http/ngx_http_request.c 221: ngx_http_init_connection
src/http/ngx_http_request.c 660: ngx_http_ssl_handshake
src/event/ngx_event_gmssl.c:479:ngx_ssl_create_connection():
src/event/ngx_event_gmssl.c:518:ngx_ssl_create_connection():
src/event/ngx_event_gmssl.c:568:ngx_ssl_handshake():
last_decrypted_block: B79C912A5A840A0A0A0A0A0A0A0A0A0A
Record
    ContentType: Handshake (22)
    Version: TLCP (1.1)
    Length: 47
    Handshake
        Type: ClientHello (1)
        Length: 43
        ClientHello
            Version: TLCP (1.1)
            Random
                gmt_unix_time : Thu Apr  8 20:28:05 2021
                random: 29783727DFE13F42F2E6CD6F49B00D79BCCDCF735C4AE937DE1263C5
            SessionID: (null)
            CipherSuites
                (null) (0x6a6a)
                TLCP_ECC_SM4_CBC_SM3 (0xe013)
            CompressionMethods
                no_compression (0)

/GmSSL-develop/src/tls12.c:697:tls12_accept():
src/event/ngx_event_gmssl.c:598:ngx_ssl_handshake():
src/http/ngx_http_request.c 802: ngx_http_ssl_handshake_handler
src/event/ngx_event_gmssl.c:1402:ngx_ssl_shutdown():
src/http/ngx_http_request.c 221: ngx_http_init_connection
src/http/ngx_http_request.c 660: ngx_http_ssl_handshake
src/event/ngx_event_gmssl.c:479:ngx_ssl_create_connection():
src/event/ngx_event_gmssl.c:518:ngx_ssl_create_connection():
src/event/ngx_event_gmssl.c:568:ngx_ssl_handshake():
last_decrypted_block: B79C912A5A840A0A0A0A0A0A0A0A0A0A
Record
    ContentType: Handshake (22)
    Version: TLCP (1.1)
    Length: 47
    Handshake
        Type: ClientHello (1)
        Length: 43
        ClientHello
            Version: TLCP (1.1)
            Random
                gmt_unix_time : Mon May 28 14:50:10 2007
                random: EB56618C91FE1BF72AEA09E567CCD5F85FDEBC382D8D05E6DB36F7EA
            SessionID: (null)
            CipherSuites
                (null) (0x2a2a)
                TLCP_ECC_SM4_CBC_SM3 (0xe013)
            CompressionMethods
                no_compression (0)

/GmSSL-develop/src/tls12.c:697:tls12_accept():
src/event/ngx_event_gmssl.c:598:ngx_ssl_handshake():
src/http/ngx_http_request.c 802: ngx_http_ssl_handshake_handler
src/event/ngx_event_gmssl.c:1402:ngx_ssl_shutdown():
src/http/ngx_http_request.c 221: ngx_http_init_connection
src/http/ngx_http_request.c 660: ngx_http_ssl_handshake
src/event/ngx_event_gmssl.c:479:ngx_ssl_create_connection():
src/event/ngx_event_gmssl.c:518:ngx_ssl_create_connection():
src/event/ngx_event_gmssl.c:568:ngx_ssl_handshake():
last_decrypted_block: B79C912A5A840A0A0A0A0A0A0A0A0A0A
Record
    ContentType: Handshake (22)
    Version: TLCP (1.1)
    Length: 47
    Handshake
        Type: ClientHello (1)
        Length: 43
        ClientHello
            Version: TLCP (1.1)
            Random
                gmt_unix_time : Sun Jun  7 03:57:44 1992
                random: BA3F1480378BE7A589E1515DEA733B302B1157C4060B4E13CC5D7CFD
            SessionID: (null)
            CipherSuites
                (null) (0x3a3a)
                TLCP_ECC_SM4_CBC_SM3 (0xe013)
            CompressionMethods
                no_compression (0)

/GmSSL-develop/src/tls12.c:697:tls12_accept():
src/event/ngx_event_gmssl.c:598:ngx_ssl_handshake():
src/http/ngx_http_request.c 802: ngx_http_ssl_handshake_handler
src/event/ngx_event_gmssl.c:1402:ngx_ssl_shutdown():

**Comment by liaoweiguo** [comment]
这就一垃圾，tls代码都注释了，打开编译不过

**Comment by zxm256** [comment]
@22826165  代码已更新
