### ISSUE TITLE
根据 issue-1304449702 可以编译，但是 stream 部分不行。

### ISSUE THREAD

**Issue by CheneyWong** [zhaoxiaomeng/Nginx-with-GmSSLv3#11]
根据 issue-1304449702 可以编译，http 部分运行正常。（部分错误，使用 C99 模式）
https://github.com/zhaoxiaomeng/Nginx-with-GmSSLv3/issues/6#issue-1304449702

但是我需要 TLS + TCP ，我添加了  --with-stream --with-stream_ssl_module， 编译就无法通过。
众多编译错误

**Comment by zxm256** [comment]
已经更新了，目前应该可以编译使用了，stream部分还在修改，如有问题请与我沟通。

**Comment by liaoweiguo** [comment]
stream很重要的，现在有些人要这东西

**Comment by lqmxiaogang** [comment]
编译了一下还是不行
./configure --prefix=/opt/gmnginx/nginx --with-http_ssl_module --with-stream  --with-stream_ssl_module --without-http_upstream_zone_module --with-debug


src/stream/ngx_stream_proxy_module.c: In function ‘ngx_stream_proxy_ssl_handshake’:
src/stream/ngx_stream_proxy_module.c:1115:18: error: implicit declaration of function ‘SSL_get_verify_result’ [-Werror=implicit-function-declaration]
 1115 |             rc = SSL_get_verify_result(pc->ssl->connection);
      |                  ^~~~~~~~~~~~~~~~~~~~~
src/stream/ngx_stream_proxy_module.c:1117:23: error: ‘X509_V_OK’ undeclared (first use in this function)
 1117 |             if (rc != X509_V_OK) {
      |                       ^~~~~~~~~
src/stream/ngx_stream_proxy_module.c:1117:23: note: each undeclared identifier is reported only once for each function it appears in
In file included from src/core/ngx_core.h:60,
                 from src/stream/ngx_stream_proxy_module.c:9:
src/stream/ngx_stream_proxy_module.c:1120:35: error: implicit declaration of function ‘X509_verify_cert_error_string’ [-Werror=implicit-function-declaration]
 1120 |                               rc, X509_verify_cert_error_string(rc));
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/ngx_log.h:86:67: note: in definition of macro ‘ngx_log_error’
   86 |     if ((log)->log_level >= level) ngx_log_error_core(level, log, __VA_ARGS__)
      |                                                                   ^~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [objs/src/stream/ngx_stream_proxy_module.o] Error 1
make[1]: Leaving directory `/opt/gmnginx/Nginx-with-GmSSLv3-master'
make: *** [build] Error 2
