### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by fishfly123** [zhaoxiaomeng/Nginx-with-GmSSLv3#12]
src/event/ngx_event_gmssl.c:499:5: error: implicit declaration of function ‘tls_set_fd’ [-Werror=implicit-function-declaration]
     if (tls_set_fd(sc->connection, c->fd) == 0) {

**Comment by zxm256** [comment]
已经更新了，目前应该可以编译使用了，如有问题请与我沟通。
