### ISSUE TITLE
配置之后443不能访问   80可以访问

### ISSUE THREAD

**Issue by gongxuanzhang** [zhaoxiaomeng/Nginx-with-GmSSLv3#13]
端口没有占用 

错误信息如下
tls_record_do_recv: Connection reset by peer
/opt/install/GmSSL/src/tls.c:1492:tls_record_do_recv():
/opt/install/GmSSL/src/tls.c:1533:tls_record_recv():
/opt/install/GmSSL/src/tls13.c:1528:tls13_do_connect():

**Comment by gzhsnail** [comment]
遇到同样的问题了，请问如何解决的？
