### ISSUE TITLE
测试通过 但是浏览器不能访问

### ISSUE THREAD

**Issue by gongxuanzhang** [zhaoxiaomeng/Nginx-with-GmSSLv3#14]
gmssl tls13_client -host 127.0.0.1 -port 443
generate handshake secrets
recv {EncryptedExtensions}
Connection established

以上  gmssl成功
但是浏览器依旧不能联通
提示以下信息    使用的是gmssl.org提供的  mac版 国密chrome   我需要配置什么吗
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by gongxuanzhang** [comment]
补充： 配置文件中 添加了 ssl_verify_client off;   仍然不可以

**Comment by bluefin1986** [comment]
同样的问题，tls13_client 连上后任意输入都没有反应

**Comment by zhuweicz** [comment]
同样问题 +1

**Comment by liuliangzzz** [comment]
同样问题 +1

**Comment by TonyLCC** [comment]
同样的问题+1111

> gmssl tls13_client -host 127.0.0.1 -port 443 generate handshake secrets recv {EncryptedExtensions} Connection established
> 
> 以上 gmssl成功 但是浏览器依旧不能联通 提示以下信息 使用的是gmssl.org提供的 mac版 国密chrome 我需要配置什么吗 ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by roman8158** [comment]
这个鬼东西不成熟啊 ，这能用吗
