### ISSUE TITLE
已经编译安装了GmSSLv3 但是configure的时候提示找不到GmSSL TLS library

### ISSUE THREAD

**Issue by greedygod** [zhaoxiaomeng/Nginx-with-GmSSLv3#15]
已安装了GmSSL 3.0.0 Beta
[root@localhost Nginx-with-GmSSLv3]# gmssl version

到安装编译安装Nginx-with-GmSSLv3的configure这步，提示
```
checking for GmSSL library ... not found

./configure: error: SSL modules require the GmSSL TLS library.
```

**Comment by greedygod** [comment]
尝试手动添加--with-gmssl=/usr/local/gmssl指定gmsslv3的安装路径，跳过了这部checking
但是遇到新的问题，见#16

**Comment by zxm256** [comment]
您可否提供一下您使用的环境？

**Comment by YangShizhao** [comment]
这个是因为gmssl默认安装到了/usr/local/lib目录下，但是这个目录不是系统的默认检索目录，需要先把这个目录加到检索列表里，然后刷新一下动态库的缓存：

```
echo "/usr/local/lib" >> /etc/ld.so.conf
ldconfig
```

刚好今天尝试配置的时候也遇到这个情况了

**Comment by greedygod** [comment]
> 您可否提供一下您使用的环境？

CentOS 7.6_x86_64

编译gmssl3.0时，手动安装了gcc9.3.0 和cmake 3.24.0 

在此基础上编译未成功

> 这个是因为gmssl默认安装到了/usr/local/lib目录下，但是这个目录不是系统的默认检索目录，需要先把这个目录加到检索列表里，然后刷新一下动态库的缓存：
> 
> ```
> echo "/usr/local/lib" >> /etc/ld.so.conf
> ldconfig
> ```
> 
> 刚好今天尝试配置的时候也遇到这个情况了

——可能有关系。我的gmsslv3编译时添加了cmake选项 `-DCMAKE_INSTALL_PREFIX=/usr/local/gmssl` 来指定安装路径

**Comment by zxm256** [comment]
我更新了一下，不知道是否解决了问题。
