### ISSUE TITLE
auto/lib/gmssl/make 没有这个make文件，但是auto/lib/make里引用到了

### ISSUE THREAD

**Issue by greedygod** [zhaoxiaomeng/Nginx-with-GmSSLv3#16]
auto/lib/make中定义了关于gmssl的make脚本
if [ $GMSSL != NONE -a $GMSSL != NO -a $GMSSL != YES ]; then
    . auto/lib/gmssl/make

但是实际上不存在这个文件，会报此
creating objs/Makefile
auto/lib/make: line 11: auto/lib/gmssl/make: No such file or directory

**Comment by james-z-repo** [comment]
I have the same problem, but there is no solution at present, is it because the GMSSL version does not correspond to it?

**Comment by zxm256** [comment]
您的编译环境是怎样的呢？

**Comment by james-z-repo** [comment]
> 您的编译环境是怎样的呢？

cmake version 3.24.0
gcc version 4.8.5 20150623
CentOS Linux release 7.5.1804 (Core)

**Comment by james-z-repo** [comment]
> 您的编译环境是怎样的呢？

我无法在项目下找到auto/lib/gmssl/make文件，它是动态生成的吗？但是我看auto/lib/perl/make文件是存在的

**Comment by greedygod** [comment]
CentOS Linux release 7.6.1810 (Core) 
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
cmake version 3.24.0

**Comment by zxm256** [comment]
解决了
