### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by liuliangzzz** [zhaoxiaomeng/Nginx-with-GmSSLv3#19]
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    sendfile        on;
    keepalive_timeout  65;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    server {
        listen       443 ssl;
        default_type text/html ;
        client_max_body_size 1000000M;
        client_body_buffer_size 3000M;
        ssl_certificate /usr/local/nginx/conf/ssl/certs.pem;
        ssl_certificate_key /usr/local/nginx/conf/ssl/signkey.pem;
        ssl_session_timeout    5m;
        location / {
            return 200;
        }
    }
}

按照文档部署完，国密浏览器报ERR_SSL_VERSION_OR_CIPHER_MISMATCH，wireshark抓包也看不到server hello协商加密套件。 
大量错误日志
![图片](https://user-images.githubusercontent.com/13974447/187710740-37200a25-c385-405e-af84-0e9ea66a97aa.png)

**Comment by statsmind** [comment]
请问这个问题解决了吗？我也遇到类似的错误

**Comment by TonyLCC** [comment]
同样的问题，测试通过，但国密浏览器提示ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by roman8158** [comment]
同问，有解决方案吗？
