### ISSUE TITLE
would  you please compile a docker image with nginx-all-modules support?

### ISSUE THREAD

**Issue by liaoweiguo** [zhaoxiaomeng/Nginx-with-GmSSLv3#2]
thanks.

I want a stream tcp port ssl, but fail with 

nginx: [emerg] unknown directive "stream" in /usr/local/nginx/conf/nginx.conf:121

**Comment by liaoweiguo** [comment]
Fail to compile --with-stream

src/http/ngx_http_upstream_round_robin.c: In function ‘ngx_http_upstream_set_round_robin_peer_session’:
src/http/ngx_http_upstream_round_robin.c:714:23: error: implicit declaration of function ‘d2i_SSL_SESSION’ [-Werror=implicit-function-declaration]
  714 |         ssl_session = d2i_SSL_SESSION(NULL, &p, len);
      |                       ^~~~~~~~~~~~~~~

**Comment by ZhangLimengLimeng** [comment]
请问有解决方法了吗？另外这个Nginx使用的是哪个版本的GmSSL？最新的编译问题更多了

**Comment by james-z-repo** [comment]
> 请问有解决方法了吗？另外这个Nginx使用的是哪个版本的GmSSL？最新的编译问题更多了

i have same question
