### ISSUE TITLE
国密库安装在指定路径时，configure报错

### ISSUE THREAD

**Issue by overzeus** [zhaoxiaomeng/Nginx-with-GmSSLv3#24]
我的国密库安装在/usr/local/gzgmssllib/目录下，当我在执行
./configure --with-http_ssl_module --without-http_upstream_zone_module --with-gmssl=/usr/local/gzgmssllib/ --with-debug
报错
![image](https://user-images.githubusercontent.com/99872205/196113214-fcd0bdcc-3116-4f43-bc00-3d0c48c0dc70.png)
请问这种情况该如何改配置文件

**Comment by kingsurprise** [comment]
我也遇到了相同的问题

**Comment by zxm256** [comment]
您是在安装GMSSLv3的时候指定了位置了吗？默认的位置应该是没有问题的

**Comment by zxm256** [comment]
应该解决了
