### ISSUE TITLE
reqsign_ext.sh执行问题

### ISSUE THREAD

**Issue by meredith233** [zhaoxiaomeng/Nginx-with-GmSSLv3#3]
执行后最终生成的cacert.pem内容为空
执行结果如下：
+ gmssl sm2keygen -pass 123456 -out cakey.pem -pubout capubkey.pem
+ gmssl certgen -C CN -ST Beijing -L Haidian -O PKU -OU CS -CN CA -days 365 -key cakey.pem -pass 123456 -out cacert.pem
certgen: '-key_usage' option required
+ gmssl certparse -in cacert.pem
+ gmssl sm2keygen -pass 123456 -out signkey.pem -pubout signpubkey.pem
+ gmssl reqgen -C CN -ST Beijing -L Haidian -O PKU -OU CS -CN Alice -days 365 -key signkey.pem -pass 123456 -out signreq.pem
+ gmssl reqsign -in signreq.pem -days 365 -key_usage digitalSignature -cacert cacert.pem -key cakey.pem -pass 123456 -out signcert.pem
reqsign: parse CA certificate failure
+ gmssl certparse -in signcert.pem
+ gmssl sm2keygen -pass 123456 -out enckey.pem -pubout encpubkey.pem
+ gmssl reqgen -C CN -ST Beijing -L Haidian -O PKU -OU CS -CN Alice -days 365 -key enckey.pem -pass 123456 -out encreq.pem
+ gmssl reqsign -in encreq.pem -days 365 -key_usage digitalSignature -cacert cacert.pem -key cakey.pem -pass 123456 -out enccert.pem
reqsign: parse CA certificate failure
+ gmssl certparse -in enccert.pem

使用docker启动该服务（编译会失败）
后续执行测试程序时报错， 端口改4443同样报错
$ ./tls12_client.sh -host 127.0.0.1 -port 443 -cacert cacert.pem
/home/mm/GmSSL/src/x509_cer.c:1694:x509_certs_new_from_file():
/home/mm/GmSSL/src/tls.c:2091:tls_ctx_set_ca_certificates():
tls12_client: context init error

**Comment by zxm256** [comment]
抱歉，前段时间太忙没来得及更新，目前已经更新
