### ISSUE TITLE
编译stream_ssl_module   报错

### ISSUE THREAD

**Issue by lsjhxl** [zhaoxiaomeng/Nginx-with-GmSSLv3#31]
编译带上--with-stream_ssl_module 发现了报错
gmssl2.5.4 还是没有问题的
看介绍 gmssl3.0 和openssl 的一些实现，移除了很多兼容性，
是否有详细一点的差异介绍
![image](https://user-images.githubusercontent.com/16043562/209926632-6ed7ac50-322c-4e99-9b3d-5adf838a5dfb.png)

**Comment by mi-sery** [comment]
同问，带了--with-stream_ssl_module就编不过了，请问有解决办法吗
