### ISSUE TITLE
编译安装Nginx-with-GmSSLv3阶段make时报错

### ISSUE THREAD

**Issue by balabaladadada** [zhaoxiaomeng/Nginx-with-GmSSLv3#4]
ngx_event_gmssl.c中的tls_recv和tls_send函数输入参数不对，请问如何解决呢

**Comment by 390620652** [comment]
我也遇到，有人来解答吗

**Comment by Linshiqi** [comment]
因为作者修改了gmssl的那些接口源码，但是nginx这快还没更新，可以先等待，或者回退提交

**Comment by zxm256** [comment]
目前已经更新，如果有问题请与我联系
