### ISSUE TITLE
国密相关的浏览器并不能正确打开页面

### ISSUE THREAD

**Issue by Bear-V** [zhaoxiaomeng/Nginx-with-GmSSLv3#40]
通过docker启动的项目，conf文件参照readme配置，且gmssl的检测命令已经成功，但是页面还是不支持打开
这里截图是奇安信的国密浏览器，360的和密信的都是类似结果
![image](https://github.com/zxm256/Nginx-with-GmSSLv3/assets/38470946/96e7b650-39f3-44cc-9ef0-7b1dbeb4b29b)

**Comment by chen914239769** [comment]
一样，我是编译安装的，https不行，http的能访问，有解决方案吗

**Comment by yanh0606** [comment]
这个项目可能不太好用，我用docker部署的也是命令监测正常，但是浏览器就是打不开，但是浏览器打开别的国密网站可以，确认不是浏览器的问题。然后我用源码编译，按照项目中的命令和步骤，结果也编译报错了，难受。。。

**Comment by chen914239769** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by chen914239769** [comment]
> 这个项目可能不太好用，我用docker部署的也是命令监测正常，但是浏览器就是打不开，但是浏览器打开别的国密网站可以，确认不是浏览器的问题。然后我用源码编译，按照项目中的命令和步骤，结果也编译报错了，难受。。。

可以试试gmssl v2版本，我已经成功了，用v3访问v2

**Comment by chen914239769** [comment]
v3不行。v2靠谱

**Comment by ifanheng** [comment]
> > 这个项目可能不太好用，我用docker部署的也是命令监测正常，但是浏览器就是打不开，但是浏览器打开别的国密网站可以，确认不是浏览器的问题。然后我用源码编译，按照项目中的命令和步骤，结果也编译报错了，难受。。。
> 
> 可以试试gmssl v2版本，我已经成功了，用v3访问v2

您好，您是怎么使用的v2，可以提供下步骤学习下吗？

**Comment by chen914239769** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Bear-V** [comment]
> > > 这个项目可能不太好用，我用docker部署的也是命令监测正常，但是浏览器就是打不开，但是浏览器打开别的国密网站可以，确认不是浏览器的问题。然后我用源码编译，按照项目中的命令和步骤，结果也编译报错了，难受。。。
> > 
> > 
> > 可以试试gmssl v2版本，我已经成功了，用v3访问v2
> 
> 您好，您是怎么使用的v2，可以提供下步骤学习下吗？

我这边偷懒了，没有自己操作，我使用了别人整合成功的docker image ，已经测试成功
dockerhub上搜不着了，名称是 keyaas2021/gmssl_nginx:v1.0
 这条命令是可用的 `docker pull keyaas2021/gmssl_nginx:v1.0`
后面附上他的博客 `https://www.cnblogs.com/gmssl/p/15267050.html`
感觉也是这个项目的某个人吧

**Comment by niceSong** [comment]
哪里来的gmssl v2 呀？

**Comment by niceSong** [comment]
> v3不行。v2靠谱

哪里来的gmssl v2 呀？

**Comment by niceSong** [comment]
> > v3不行。v2靠谱

成功了，确实可行
