### ISSUE TITLE
给大家提供一个临时解决方案，关于make时报错问题

### ISSUE THREAD

**Issue by meredith233** [zhaoxiaomeng/Nginx-with-GmSSLv3#6]
在编译安装GmSSL3.0
原本需要执行的命令如下，但由于GmSSL更新了版本，而本项目没有更新，所以后续在构建本项目时会报错
```gmssl@ubuntu:~/nginx_doc$ git clone https://github.com/guanzhi/GmSSL.git
gmssl@ubuntu:~/nginx_doc$ cd GmSSL/
gmssl@ubuntu:~/nginx_doc/GmSSL$ mkdir build
gmssl@ubuntu:~/nginx_doc/GmSSL$ cd build/
gmssl@ubuntu:~/nginx_doc/GmSSL/build$ cmake ..
gmssl@ubuntu:~/nginx_doc/GmSSL/build$ make
gmssl@ubuntu:~/nginx_doc/GmSSL/build$ sudo make install


解决方案如下：
gmssl@ubuntu:~/nginx_doc$ git clone https://github.com/guanzhi/GmSSL.git
gmssl@ubuntu:~/nginx_doc$ cd GmSSL/
// 加了以下步骤，将GmSSL版本回滚
gmssl@ubuntu:~/nginx_doc/GmSSL$ git reset --hard 1c02e18fcdf63ced3b728a1962047d8c292f47ed
gmssl@ubuntu:~/nginx_doc/GmSSL$ mkdir build
gmssl@ubuntu:~/nginx_doc/GmSSL$ cd build/
gmssl@ubuntu:~/nginx_doc/GmSSL/build$ cmake ..
gmssl@ubuntu:~/nginx_doc/GmSSL/build$ make
gmssl@ubuntu:~/nginx_doc/GmSSL/build$ sudo make install

实测可正常make该项目

**Comment by xcw233** [comment]
回滚方案有效！
我编译的时候
在GMSSL回滚以后，
make会出现一个异常
![image](https://user-images.githubusercontent.com/56435763/179474009-e7377b18-50a1-4d21-95ec-c3bbc96a1e3a.png)
这个问题只需要到 GmSSL/src/des.c文件里把for里面变量i的定义，定义放到外面就行。
![image](https://user-images.githubusercontent.com/56435763/179474481-24de6a1e-d88e-4a5a-a483-71a0b124176e.png)

**Comment by xcw233** [comment]
> 在编译安装GmSSL3.0 原本需要执行的命令如下，但由于GmSSL更新了版本，而本项目没有更新，所以后续在构建本项目时会报错
> 
> ```
> gmssl@ubuntu:~/nginx_doc$ cd GmSSL/
> gmssl@ubuntu:~/nginx_doc/GmSSL$ mkdir build
> gmssl@ubuntu:~/nginx_doc/GmSSL$ cd build/
> gmssl@ubuntu:~/nginx_doc/GmSSL/build$ cmake ..
> gmssl@ubuntu:~/nginx_doc/GmSSL/build$ make
> gmssl@ubuntu:~/nginx_doc/GmSSL/build$ sudo make install
> 
> 
> 解决方案如下：
> gmssl@ubuntu:~/nginx_doc$ git clone https://github.com/guanzhi/GmSSL.git
> gmssl@ubuntu:~/nginx_doc$ cd GmSSL/
> // 加了以下步骤，将GmSSL版本回滚
> gmssl@ubuntu:~/nginx_doc/GmSSL$ git reset --hard 1c02e18fcdf63ced3b728a1962047d8c292f47ed
> gmssl@ubuntu:~/nginx_doc/GmSSL$ mkdir build
> gmssl@ubuntu:~/nginx_doc/GmSSL$ cd build/
> gmssl@ubuntu:~/nginx_doc/GmSSL/build$ cmake ..
> gmssl@ubuntu:~/nginx_doc/GmSSL/build$ make
> gmssl@ubuntu:~/nginx_doc/GmSSL/build$ sudo make install
> 
> 实测可正常make该项目
> ```

你好，请问你编译出来的nginx，按照readme中给出的方式配置了国密server以后，能否使用国密浏览器访问，并成功建立国密通道？
我编译好的nginx，当使用国密浏览器访问的时候nginx的错误日志如下
![image](https://user-images.githubusercontent.com/56435763/179501637-8ebae59d-0d99-4b6a-bf68-b36ed7acd503.png)
我的国密server配置
![image](https://user-images.githubusercontent.com/56435763/179501858-36e0a030-ecd0-4d08-afbb-73572bd1a61e.png)
其中的证书是使用reqsign_ext.sh脚本生成的。

**Comment by meredith233** [comment]
> > 在编译安装GmSSL3.0 原本需要执行的命令如下，但由于GmSSL更新了版本，而本项目没有更新，所以后续在构建本项目时会报错
> > ```
> > gmssl@ubuntu:~/nginx_doc$ cd GmSSL/
> > gmssl@ubuntu:~/nginx_doc/GmSSL$ mkdir build
> > gmssl@ubuntu:~/nginx_doc/GmSSL$ cd build/
> > gmssl@ubuntu:~/nginx_doc/GmSSL/build$ cmake ..
> > gmssl@ubuntu:~/nginx_doc/GmSSL/build$ make
> > gmssl@ubuntu:~/nginx_doc/GmSSL/build$ sudo make install
> > 
> > 
> > 解决方案如下：
> > gmssl@ubuntu:~/nginx_doc$ git clone https://github.com/guanzhi/GmSSL.git
> > gmssl@ubuntu:~/nginx_doc$ cd GmSSL/
> > // 加了以下步骤，将GmSSL版本回滚
> > gmssl@ubuntu:~/nginx_doc/GmSSL$ git reset --hard 1c02e18fcdf63ced3b728a1962047d8c292f47ed
> > gmssl@ubuntu:~/nginx_doc/GmSSL$ mkdir build
> > gmssl@ubuntu:~/nginx_doc/GmSSL$ cd build/
> > gmssl@ubuntu:~/nginx_doc/GmSSL/build$ cmake ..
> > gmssl@ubuntu:~/nginx_doc/GmSSL/build$ make
> > gmssl@ubuntu:~/nginx_doc/GmSSL/build$ sudo make install
> > 
> > 实测可正常make该项目
> > ```
> 
> 你好，请问你编译出来的nginx，按照readme中给出的方式配置了国密server以后，能否使用国密浏览器访问，并成功建立国密通道？ 我编译好的nginx，当使用国密浏览器访问的时候nginx的错误日志如下 ![image](https://user-images.githubusercontent.com/56435763/179501637-8ebae59d-0d99-4b6a-bf68-b36ed7acd503.png) 我的国密server配置 ![image](https://user-images.githubusercontent.com/56435763/179501858-36e0a030-ecd0-4d08-afbb-73572bd1a61e.png) 其中的证书是使用reqsign_ext.sh脚本生成的。

我在对GmSSL回滚后，在对GmSSL进行make时没有报错，可能和g++版本有关系
我的cmake安装方式
https://www.yuque.com/docs/share/fad8c36a-a36f-499e-b511-f4d1422ce84d?# 《cmake on Ubuntu》

后续也没有遇到什么问题，根据README进行配置后，查看reqsign_ext.sh生成的文件里面均有内容（之前没有回滚GmSSL直接生成会导致部分文件内容为空）

用以下命令进行了测试，也没有报错
https://github.com/zhaoxiaomeng/Nginx-with-GmSSLv3#%E6%B5%8B%E8%AF%95nginx

**Comment by xcw233** [comment]
> > > 在编译安装GmSSL3.0 原本需要执行的命令如下，但由于GmSSL更新了版本，而本项目没有更新，所以后续在构建本项目时会报错
> > > ```
> > > gmssl@ubuntu:~/nginx_doc$ cd GmSSL/
> > > gmssl@ubuntu:~/nginx_doc/GmSSL$ mkdir build
> > > gmssl@ubuntu:~/nginx_doc/GmSSL$ cd build/
> > > gmssl@ubuntu:~/nginx_doc/GmSSL/build$ cmake ..
> > > gmssl@ubuntu:~/nginx_doc/GmSSL/build$ make
> > > gmssl@ubuntu:~/nginx_doc/GmSSL/build$ sudo make install
> > > 
> > > 
> > > 解决方案如下：
> > > gmssl@ubuntu:~/nginx_doc$ git clone https://github.com/guanzhi/GmSSL.git
> > > gmssl@ubuntu:~/nginx_doc$ cd GmSSL/
> > > // 加了以下步骤，将GmSSL版本回滚
> > > gmssl@ubuntu:~/nginx_doc/GmSSL$ git reset --hard 1c02e18fcdf63ced3b728a1962047d8c292f47ed
> > > gmssl@ubuntu:~/nginx_doc/GmSSL$ mkdir build
> > > gmssl@ubuntu:~/nginx_doc/GmSSL$ cd build/
> > > gmssl@ubuntu:~/nginx_doc/GmSSL/build$ cmake ..
> > > gmssl@ubuntu:~/nginx_doc/GmSSL/build$ make
> > > gmssl@ubuntu:~/nginx_doc/GmSSL/build$ sudo make install
> > > 
> > > 实测可正常make该项目
> > > ```
> > 
> > 
> > 你好，请问你编译出来的nginx，按照readme中给出的方式配置了国密server以后，能否使用国密浏览器访问，并成功建立国密通道？ 我编译好的nginx，当使用国密浏览器访问的时候nginx的错误日志如下 ![image](https://user-images.githubusercontent.com/56435763/179501637-8ebae59d-0d99-4b6a-bf68-b36ed7acd503.png) 我的国密server配置 ![image](https://user-images.githubusercontent.com/56435763/179501858-36e0a030-ecd0-4d08-afbb-73572bd1a61e.png) 其中的证书是使用reqsign_ext.sh脚本生成的。
> 
> 我在对GmSSL回滚后，在对GmSSL进行make时没有报错，可能和g++版本有关系 我的cmake安装方式 https://www.yuque.com/docs/share/fad8c36a-a36f-499e-b511-f4d1422ce84d?# 《cmake on Ubuntu》
> 
> 后续也没有遇到什么问题，根据README进行配置后，查看reqsign_ext.sh生成的文件里面均有内容（之前没有回滚GmSSL直接生成会导致部分文件内容为空）
> 
> 用以下命令进行了测试，也没有报错 https://github.com/zhaoxiaomeng/Nginx-with-GmSSLv3#%E6%B5%8B%E8%AF%95nginx

你好，请问，你在国密server配置完成以后，是否有使用国密浏览器对Nginx进行访问呢，能正常访问吗？谢谢！

**Comment by zxm256** [comment]
sorry，最近比较忙没来得及维护，近期我们会修改和gmssl版本不兼容的bug问题

**Comment by xcw233** [comment]
> 

谢谢，辛苦了！

**Comment by xcw233** [comment]
> sorry，最近比较忙没来得及维护，近期我们会修改和gmssl版本不兼容的bug问题
谢谢，辛苦了！

**Comment by zxm256** [comment]
@xcw233 @meredith233 目前已经更新了，应该可以编译使用了，如有问题请与我沟通。
